name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    permissions:
      id-token: write 
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: 'Az CLI login using cloud neutral identity'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: 'Deploy container to Azure'
        run: |
          az webapp up --location westus --name strockis-github-demo --html
      - name: 'Deploy container to GCP using Google Cloud SDK'
        run: echo "Deploying container to GKE..."